apiVersion: apps/v1
kind: Deployment
metadata:
  name: twig-backend
  namespace: production
  labels:
    app: twig
    component: backend
    environment: production
    version: "v2.1.0"
  annotations:
    deployment.kubernetes.io/revision: "1"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twig
      component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: twig
        component: backend
    spec:
      serviceAccountName: twig-backend-sa
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: api-server
        image: ghcr.io/workdone0/twig-backend:v2.1.0-sha256
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: twig-db-credentials
              key: connection_string
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: twig-config
              key: redis_url
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: config-volume
        configMap:
          name: twig-config
      - name: tmp-volume
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - twig
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: twig-backend-service
  namespace: production
  labels:
    app: twig
spec:
  type: ClusterIP
  selector:
    app: twig
    component: backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
